apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: angular
spec:
  template:
    spec:
      containers:
        - image: registry.hub.docker.com/witoonruamngoen/angular
          ports:
            - name: http1
              containerPort: 80
              